### ISSUE TITLE
Add missing network policy label

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/virtual-garden#12]
**How to categorize this issue?**

/area TODO
/kind bug
/priority 3

**What happened**:
The virtual garden API server pods miss the network policy label:

```
networking.gardener.cloud/to-gardenlogin-controller-manager: allowed
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Landscaper Component version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ghost** [comment]
@danielfoehrKn Label area/todo does not exist.
