### ISSUE TITLE
add optional ready check for exported target

### ISSUE THREAD

**Issue by reshnm** [gardener/virtual-garden#8]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 4

**What would you like to be added**:

Currently the exported target  `virtualGardenKubeconfig`, resp. the Kube API server that is represented by the target, is not _ready_ when the reconcile has finished.
Not _ready_ means, connections to the Kube API server will fail until bootstrapping is completed.

Subsequent installations, that use the exported target have to implement a _readyness check_ on their own.
It would be helpful to add an optional _readyness check_ (with a timeout) to the virtual garden deployment where the reconcile only finishes when the Kube API server is ready to accept incoming connections.

**Comment by achimweigel** [comment]
This is a good idea, we just implemented in this [PR](https://github.com/gardener/virtual-garden/pull/7)

**Comment by reshnm** [comment]
@achimweigel Thank you!
